### ISSUE TITLE
things change, i think for the best

### ISSUE THREAD

**Issue by jukefr** [jukefr/jukefr#6]
The world changes, and I think it's for the best, even if sometimes it might seem a bit forced and with little room for debate
I have recently come to the conclusion that any kind of intolerance towards **anybody** no matter if its for a "joke" or whatever can be interpreted as hurtful by **at least a single person** and that is not fine with me, I do not want to hurt anybody period.
There are places where a freer discourse may be acceptable in my eyes, such as conversations with people who already understand whatever context might lead up to a spicy joke or whatever. the world is already a sad enough place as it is today for me to add my garbage on top of it.
Reductio ad Hitlerum, but the way I see it if we don't allow Nazis even the slightest room for growth (which I understand why), I don't think that the current "alt right" and all the "edgy" and "anti-PC" (which I honestly would have identified as for the longest time until now, the anti-PC part, nothing else 😅) community and such lands very far from Nazism......

I am more than willing to trade a few spicy jokes for the happiness of other people

This mainly means removing anything that may be perceived as hurtful to anyone from every repository history I own.
Also, I want to learn how to properly phrase gender-neutral stuff to update every instruction there might be.
There may be some more stuff to do but I can only think of this for now

**Comment by jukefr** [comment]
https://writingcenter.unc.edu/tips-and-tools/gender-inclusive-language/

**Comment by PragmaTwice** [comment]
> **To the ambush mob who is ganging up on Richard Stallman over reasonable arguments in debate and various opinions and beliefs voiced over decades as a public figure:**
> You have no part in choosing the leadership of any communities. Especially not via another mob attack which does not remotely resemble a fairly conducted debate as exemplified by better people such as Richard Stallman.

*from **An open letter in support of Richard M. Stallman***

**Comment by jukefr** [comment]
imagine having nothing better to do with your life, sigh
anyways this was already done, closing
